name: Deploy nest app
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run linter
        run: npm run lint
      - name: Build app
        run: npm run build
      - name: Deploy app
        run: echo Deploy
