name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository code
        uses: actions/checkout@v3
      - name: Install deps
        uses: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
