name: Check
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18]

    name: Node ${{ matrix.node }} sample

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install devs
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node: [16, 18]

    - name: Checkout
      uses: actions/checkout@v3
    - name: Install devs
      run: npm ci
    - name: Run tests
      run: npm run test