name: Deploy Nest app
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository code
        uses: actions/checkout@v3
      - name: Use cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hash('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository code
        uses: actions/checkout@v3
      - name: Use cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hash('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  build:
    needs: [lint, test]

    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Copy repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version  }}
      - name: Use cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hash('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Deploy
        run: echo Deploying...
